---
"on":
  schedule:
    # 18:00 on Friday
    - cron: 0 18 * * 5
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/orgs/community/discussions/25702
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install po4a
      - name: Update version
        id: version
        run: |
          scripts/git-commit.sh
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
      - uses: Freed-Wu/translate-shell@0.0.32
        with:
          files: |
            po4a/zh_CN/*.po
      - name: Git commit
        run: |
          scripts/post-git-commit.sh
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
